name: Build and Deploy React Frontend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Setup Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3.2.0
      with:
        node-version: '20.11.1'

    - name: Install Dependencies
      run: npm install
      working-directory: ${{ github.workspace }}/foodProjectSpringBoot/src/main/webapp/app

    - name: Build React project
      run: npm run build
      working-directory: ${{ github.workspace }}/foodProjectSpringBoot/src/main/webapp/app

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./foodProjectSpringBoot/src/main/webapp/app  # Adjusted context for Docker build
        file: ./foodProjectSpringBoot/src/main/webapp/app/Dockerfile
        tags: ringo1225/dmss_frontend:latest
        push: true
        secrets: dckr_pat_Q2aNfZY2BhkwCaNd3Ed7Vqnubco
