name: Java and React Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2.4.0

    # Setup Java environment with JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Build and Test Spring Boot Application
    - name: Build and test Spring Boot
      run: |
        cd ${{ github.workspace }}/foodProjectSpringBoot
        mvn clean compile

    # Setup Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3.2.0
      with:
        node-version: '20.11.1'

    # Debug: Show workspace directory structure
    - name: Debug
      run: ls -R $GITHUB_WORKSPACE

    # Install Node.js dependencies for React application
    - name: Install React dependencies
      run: npm install
      working-directory: ${{ github.workspace }}/foodProjectSpringBoot/src/main/webapp/app

    # Build React application
    - name: Build React app
      run: npm run build
      working-directory: ${{ github.workspace }}/foodProjectSpringBoot/src/main/webapp/app

    # Optionally, add steps to test the React application if you have tests set up
    - name: Test React app
      run: npm test
      working-directory: ${{ github.workspace }}/foodProjectSpringBoot/src/main/webapp/app
